export const productions: Record<number, { lhs: string, rhs: string[] }> = {
  0: { lhs: "program", rhs: ["def_list"] },
  1: { lhs: "def_list", rhs: ["def_list", "def"] },
  2: { lhs: "def_list", rhs: [] }, 
  3: { lhs: "def", rhs: ["var_def"] },
  4: { lhs: "def", rhs: ["fun_def"] },
  5: { lhs: "var_def", rhs: ["var", "var_list", ";"] },
  6: { lhs: "var_list", rhs: ["id_list"] },
  7: { lhs: "id_list", rhs: ["id", "id_list_cont"] },
  8: { lhs: "id_list_cont", rhs: [",", "id", "id_list_cont"] },
  9: { lhs: "id_list_cont", rhs: [] },
  10: { lhs: "fun_def", rhs: ["id", "(", "param_list", ")", "{", "var_def_list", "stmt_list", "}"] },
  11: { lhs: "param_list", rhs: ["id_list"] },
  12: { lhs: "param_list", rhs: [] },
  13: { lhs: "var_def_list", rhs: ["var_def_list", "var_def"] },
  14: { lhs: "var_def_list", rhs: [] },
  15: { lhs: "stmt_list", rhs: ["stmt_list", "stmt"] },
  16: { lhs: "stmt_list", rhs: [] },
  17: { lhs: "stmt", rhs: ["stmt_assign"] },
  18: { lhs: "stmt", rhs: ["stmt_incr"] },
  19: { lhs: "stmt", rhs: ["stmt_decr"] },
  20: { lhs: "stmt", rhs: ["stmt_fun_call"] },
  21: { lhs: "stmt", rhs: ["stmt_if"] },
  22: { lhs: "stmt", rhs: ["stmt_loop"] },
  23: { lhs: "stmt", rhs: ["stmt_break"] },
  24: { lhs: "stmt", rhs: ["stmt_return"] },
  25: { lhs: "stmt", rhs: ["stmt_empty"] },
  26: { lhs: "stmt_assign", rhs: ["id", "=", "expr", ";"] },
  27: { lhs: "stmt_incr", rhs: ["inc", "id", ";"] },
  28: { lhs: "stmt_decr", rhs: ["dec", "id", ";"] },
  29: { lhs: "stmt_fun_call", rhs: ["fun_call", ";"] },
  30: { lhs: "fun_call", rhs: ["id", "(", "expr_list", ")"] },
  31: { lhs: "expr_list", rhs: ["expr", "expr_list_cont"] },
  32: { lhs: "expr_list", rhs: [] },
  33: { lhs: "expr_list_cont", rhs: [",", "expr", "expr_list_cont"] },
  34: { lhs: "expr_list_cont", rhs: [] },
  35: { lhs: "stmt_if", rhs: ["if", "(", "expr", ")", "{", "stmt_list", "}", "else_if_list", "else"] },
  36: { lhs: "else_if_list", rhs: ["else_if_list", "elif", "(", "expr", ")", "{", "stmt_list", "}"] },
  37: { lhs: "else_if_list", rhs: [] },
  38: { lhs: "else", rhs: ["else", "{", "stmt_list", "}"] },
  39: { lhs: "else", rhs: [] },
  40: { lhs: "stmt_loop", rhs: ["loop", "{", "stmt_list", "}"] },
  41: { lhs: "stmt_break", rhs: ["break", ";"] },
  42: { lhs: "stmt_return", rhs: ["return", "expr", ";"] },
  43: { lhs: "stmt_empty", rhs: [";"] },
  44: { lhs: "expr", rhs: ["expr_or"] },
  45: { lhs: "expr_or", rhs: ["expr_or", "or", "expr_and"] },
  46: { lhs: "expr_or", rhs: ["expr_and"] },
  47: { lhs: "expr_and", rhs: ["expr_and", "and", "expr_comp"] },
  48: { lhs: "expr_and", rhs: ["expr_comp"] },
  49: { lhs: "expr_comp", rhs: ["expr_comp", "op_comp", "expr_rel"] },
  50: { lhs: "expr_comp", rhs: ["expr_rel"] },
  51: { lhs: "op_comp", rhs: ["=="] },
  52: { lhs: "op_comp", rhs: ["!="] },
  53: { lhs: "expr_rel", rhs: ["expr_rel", "op_rel", "expr_add"] },
  54: { lhs: "expr_rel", rhs: ["expr_add"] },
  55: { lhs: "op_rel", rhs: ["<"] },
  56: { lhs: "op_rel", rhs: ["<="] },
  57: { lhs: "op_rel", rhs: [">"] },
  58: { lhs: "op_rel", rhs: [">="] },
  59: { lhs: "expr_add", rhs: ["expr_add", "op_add", "expr_mul"] },
  60: { lhs: "expr_add", rhs: ["expr_mul"] },
  61: { lhs: "op_add", rhs: ["+"] },
  62: { lhs: "op_add", rhs: ["-"] },
  63: { lhs: "expr_mul", rhs: ["expr_mul", "op_mul", "expr_unary"] },
  64: { lhs: "expr_mul", rhs: ["expr_unary"] },
  65: { lhs: "op_mul", rhs: ["*"] },
  66: { lhs: "op_mul", rhs: ["/"] },
  67: { lhs: "op_mul", rhs: ["%"] },
  68: { lhs: "expr_unary", rhs: ["op_unary", "expr_unary"] },
  69: { lhs: "expr_unary", rhs: ["expr_primary"] },
  70: { lhs: "op_unary", rhs: ["+"] },
  71: { lhs: "op_unary", rhs: ["-"] },
  72: { lhs: "op_unary", rhs: ["not"] },
  73: { lhs: "expr_primary", rhs: ["id"] },
  74: { lhs: "expr_primary", rhs: ["fun_call"] },
  75: { lhs: "expr_primary", rhs: ["array"] },
  76: { lhs: "expr_primary", rhs: ["lit"] },
  77: { lhs: "expr_primary", rhs: ["(", "expr", ")"] },
  78: { lhs: "array", rhs: ["[", "expr_list", "]"] },
  79: { lhs: "lit", rhs: ["lit_bool"] },
  80: { lhs: "lit", rhs: ["lit_int"] },
  81: { lhs: "lit", rhs: ["lit_char"] },
  82: { lhs: "lit", rhs: ["lit_str"] },
};